[tool.poetry]
name = "TemplateProject"
version = "0.1.0"
description = ""
authors = ["stepa <gavrilovstepan78@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.75.1"
psycopg2 = "^2.9.3"
tortoise-orm = "^0.19.0"
aerich = "^0.6.2"
uvicorn = "^0.17.6"
gunicorn = "^20.1.0"
install = "^1.3.5"
allure-pytest = "^2.9.45"
flake8 = "^4.0.1"
mypy = "^0.942"
types-requests = "^2.27.16"
pytest = "^7.1.1"
docker = "^5.0.3"
pyparsing = "^3.0.6"
pip = "^22.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
