{
 "title": "Careful profiling",
 "tags": [
  "Careful profiling",
  "postgres"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Calls by request",
   "type": "graph",
   "description": "Calls by request",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_stat_long_consuming_calls", "legendFormat": "{{ query }}" }
   ]
  },
  {
   "title": "Time spent by request",
   "type": "graph",
   "description": "Time spent by request",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_long_consuming_total_time_seconds",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Mean time by request",
   "type": "graph",
   "description": "Mean time by request",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_long_consuming_mean_time_seconds",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Input / Output instructions by request",
   "type": "graph",
   "description": "Input / Output instructions by request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_top_io_mean_time_seconds",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Max time by request",
   "type": "graph",
   "description": "Max time by request",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_long_consuming_max_time_seconds",
     "legendFormat": "{{ query  }}"
    }
   ]
  },
  {
   "title": "Execution max time",
   "type": "graph",
   "description": "Execution max time",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_long_consuming_max_time_seconds",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Memory using by request",
   "type": "graph",
   "description": "Memory using by request",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_memory_live_using_memory",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}