"""initial

Revision ID: 1eb35e7eb219
Revises: 
Create Date: 2022-08-26 19:37:56.034238

"""
import sqlalchemy_utils  # type: ignore
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1eb35e7eb219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('username', sa.String(length=32), nullable=False),
                    sa.Column('password', sa.String(length=512), nullable=False),
                    sa.Column('is_blocked', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
                              nullable=True),
                    sa.Column('country', sa.String(length=32), nullable=True),
                    sa.Column('job', sa.String(length=32), nullable=True),
                    sa.Column('company', sa.String(length=32), nullable=True),
                    sa.Column('age', sa.SmallInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_Account_id'), 'Account', ['id'], unique=False)
    # ### end Alembic commands ###
