global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:

  - job_name: "node"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "postgres-exporter"
    metrics_path: "/metrics"
    honor_labels: true
    static_configs:
      - targets: [ 'postgres-exporter-pgserver94:9187' ]

  - job_name: "redis_exporter"
    static_configs:
      - targets: [ 'redis-exporter:9121' ]