global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - 0.0.0.0:9090

#  - job_name: minio-job
#    metrics_path: /minio/v2/metrics/cluster
#    scheme: http
#    static_configs:
#      - targets:
#          - "minio:9000"
#          - "node-exporter:9100"

  - job_name: "node"
    static_configs:
      - targets: [ "node-exporter:9100" ]