name: Build

on:
  push:
    branches-ignore:
      - '!dependabot/**'

jobs:

  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.10.2 ]
        poetry-version: [ 1.1.11 ]
        os: [ ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run mypy
        run: poetry run mypy . --config-file=mypy.ini

      - name: Run tests
        run: poetry run python -m unittest discover

      # BADGES
      # create file structure for badges
      - name: Create dirs for badges
        run: mkdir -p report2 && mkdir -p reports/coverage && mkdir -p reports/flake8 && mkdir -p reports/junit

      # run analyzer tools for badges
      - name: Create coverage response (1/2)
        run: poetry run coverage run -m unittest discover

      - name: Create coverage response (2/2)
        run: poetry run coverage xml -o reports/coverage/coverage.xml

      - name: Create pytest response
        run: poetry run pytest --junitxml=reports/junit/junit.xml

      - name: Create flake
        run: poetry run flake8 --output-file=reports/flake8/flake8stats.txt

      # create new badges
      - name: Create badge for coverage
        run: poetry run genbadge coverage

      - name: Create badge for flake8
        run: poetry run genbadge flake8

      - name: Create badge for tests
        run: poetry run genbadge tests

      - name: Commit badges files
        run: |
          git config --local user.email ${{github.event.pusher.email}}
          git config --local user.name ${{ github.actor }}
          git add /home/runner/work/TemplateModernProject/TemplateModernProject/tests-badge.svg
          git add /home/runner/work/TemplateModernProject/TemplateModernProject/flake8-badge.svg
          git add /home/runner/work/TemplateModernProject/TemplateModernProject/coverage-badge.svg
          git commit --allow-empty -m "Add artifacts"
      - name: Push badges changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true